import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "One Point Up",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className="min-h-screen bg-[var(--background)]">
                <div
                    className="
                        mx-auto w-full max-w-[600px] min-h-dvh bg-white
                        pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]
                        overflow-y-auto
                    "
                >
                    {children}
                </div>

                <Toaster
                    position="top-center"
                    toastOptions={{
                        duration: 2000,
                        style: {
                            fontSize: "14px",
                            fontWeight: 500,
                            borderRadius: "10px",
                            padding: "10px 14px",
                        },
                    }}
                />
            </body>
        </html>
    );
}
